// Scenario content for the interactive prototype.
// One flow per Table 3 S/N plus a cross-cutting group. Each step shows an app
// screen, a portal screen, or both (cause → effect). Edit freely; no build needed.
//
// step fields:
//   app / portal  screen ids (at least one)      focus   'app' | 'portal' (which frame is primary when both)
//   title         short label                    actor   who is looking at the screen
//   note          1–3 sentences on what the screen proves
//   pins          [{match, text, in?}] numbered callouts; match = visible text on the primary frame
//   tryIt         what to tap to move on          ref     where this sits in the written proposal

window.FLOW_META = {
  title: 'Attachment 7-B · Interactive prototype',
  subtitle: 'CPF Volunteer app and Administrator Portal · Table 3 S/N 23–30',
  tender: 'CPFOPD2026TDR049 · Part 2 §2.1(h) · Section 7 §7.4',
};

window.FLOWS = [
  {
    id: '23', sn: 'S/N 23', title: 'Feedback form', phase: 'Phase 2',
    intro: 'A volunteer or admin given the Support role for specific event slots rates the volunteers on that slot using a form built from a template in the Portal. Volunteers see only the fields CPFB marks as shareable.',
    rules: [
      'Only users given the Support role for a slot see its roster (23-01, 23-02).',
      'A support user cannot rate themselves (23-03).',
      'Drafts persist through the in-app browser and app restarts (23-06).',
      'Submitted and auto-rated feedback is read-only (23-08, 23-09).',
      'Volunteers see only shareable fields; a 5 of 5 awards CPFV points (23-12, 23-13).',
      'If no feedback is given by the set date, the default rating is applied and marked Auto-rated (23-17).',
    ],
    steps: [
      { app: '23-01', title: 'Home: support entry point', actor: 'Support-role user',
        note: 'A new card appears on Home only for users holding the Support role. The badge counts assignments that still have feedback outstanding. Nothing else on Home moves.',
        pins: [{ match: 'My support assignments', text: 'New card, indigo border marks it as new in this proposal' }, { match: '3 volunteers need your feedback', text: 'Outstanding count, same number as the push reminder' }],
        tryIt: 'Tap the “My support assignments” card.', ref: '§7.4 · S/N 23 · App 1' },
      { app: '23-02', title: 'Support assignments list', actor: 'Support-role user',
        note: 'Lives in Collaborate → My Activities, above the user’s own registrations. Events are grouped by date; the slot chip shows only the slot this user is tagged to.',
        pins: [{ match: 'Support assignments', text: 'New section, count badge' }, { match: '3 feedback pending', text: 'Per-event outstanding count' }, { match: 'View roster', text: 'Opens the roster for the tagged slot' }],
        tryIt: 'Tap “View roster”.', ref: '§7.4 · S/N 23 · App 2' },
      { portal: '23-17', app: '23-02', focus: 'portal', title: 'Where it comes from: event card settings', actor: 'Admin User',
        note: 'The event card gains a “Support & feedback” tab. Enabling the support role, assigning users per slot, picking the template, the reminder rule and the default rating all happen here. The phone on the right is what the assigned user then sees.',
        pins: [{ match: 'Enable support role', text: 'Master switch per event' }, { match: 'Assign support users to slots', text: 'Search + multi-select per slot' }, { match: 'Reminder rule', text: 'N days after event OR fixed day of month' }, { match: 'Default rating', text: 'Applied on a set date if no feedback is given' }],
        tryIt: 'Tap “Enable support role” to jump to the app’s Home, or Next.', ref: '§7.4 · S/N 23 · Portal 13' },
      { app: '23-03', title: 'Volunteer roster', actor: 'Support-role user',
        note: 'Each row pairs attendance status with feedback status. The rule is shown, not just stated: the support user is on this slot too, so they are excluded from their own roster.',
        pins: [{ match: "You're on this slot too", text: 'Cannot rate self' }, { match: 'Auto-rated', text: 'Default rating applied after the deadline' }, { match: 'Attendance QR', text: 'Full-screen code for this slot' }],
        tryIt: 'Tap “Attendance QR”, or a volunteer row to open their form.', ref: '§7.4 · S/N 23 · App 3' },
      { app: '23-04', title: 'Attendance QR', actor: 'Support-role user',
        note: 'Full-screen code for the tagged slot only. The code rotates so a screenshot cannot be reused later; brightness is raised automatically.',
        pins: [{ match: 'Code refreshes in', text: 'Rotating code' }, { match: 'Screen brightness raised', text: 'Scannable outdoors' }],
        tryIt: 'Tap “Done” to go back.', ref: '§7.4 · S/N 23 · App 4' },
      { app: '23-05', title: 'Feedback form, fields 1–4', actor: 'Support-role user',
        note: 'Rendered from the “Outreach shift v2” template. Rating, quick-reaction chips, single choice and free text are the first four of the seven field types. The draft autosaves.',
        pins: [{ match: 'Template: Outreach shift v2', text: 'Form is template-driven' }, { match: 'Draft saved 2 min ago', text: 'Autosave' }, { match: 'Shared with volunteer', text: 'Field marked shareable in the template' }],
        tryIt: 'Tap the Comments card to continue to fields 5–7.', ref: '§7.4 · S/N 23 · App 5' },
      { app: '23-06', title: 'Fields 5–7, back from the in-app browser', actor: 'Support-role user',
        note: 'Dropdown, attachment and external URL complete the seven types. The external link opened in the in-app browser; on return the draft is exactly as it was and a banner says so.',
        pins: [{ match: 'Welcome back', text: 'Draft restored after the browser' }, { match: 'route-photo.jpg', text: 'PDF / JPEG / PNG tile with preview' }, { match: 'Open incident log form', text: 'External URL, draft is kept' }],
        tryIt: 'Tap “Submit”.', ref: '§7.4 · S/N 23 · App 5' },
      { app: '23-07', title: 'Validation errors', actor: 'Support-role user',
        note: 'Submitting with required fields empty shows a summary at the top and an inline message on each field. The draft stays saved; nothing is lost.',
        pins: [{ match: '2 fields need attention', text: 'Summary first, then inline' }, { match: 'Choose a rating from 1 to 5', text: 'Inline error, text not colour alone' }],
        tryIt: 'Tap “Save draft”.', ref: '§7.4 · S/N 23 · App 6' },
      { app: '23-08', title: 'Submitted, read-only', actor: 'Support-role user',
        note: 'Once submitted the form is locked. All answers are shown in the order of the template, including fields that will not be shared with the volunteer.',
        pins: [{ match: "Submitted feedback can't be edited.", text: 'Read-only rule' }, { match: 'Read-only', text: 'Replaces Save / Submit' }],
        tryIt: 'Use the back arrow.', ref: '§7.4 · S/N 23 · App 6' },
      { app: '23-09', title: 'Incomplete and Completed tabs', actor: 'Support-role user',
        note: 'The rounded segmented toggle is the one used for Missions | VFTP. Anything under Incomplete can still be edited; Completed and Auto-rated are view-only.',
        pins: [{ match: 'Incomplete (3)', text: 'Editable' }, { match: 'Completed (2)', text: 'View-only' }, { match: 'default', text: 'Auto-rated after the deadline' }],
        tryIt: 'Tap “Continue” to resume the draft.', ref: '§7.4 · S/N 23 · App 7' },
      { app: '23-10', title: 'Reminder push', actor: 'Support-role user',
        note: 'Push plus in-app reminder, timed by the rule set on the event card. It names the event and the number of volunteers still waiting; tapping opens the Incomplete tab.',
        pins: [{ match: 'Feedback reminder', text: 'Repeats per the reminder rule' }],
        tryIt: 'Tap the notification.', ref: '§7.4 · S/N 23 · App 8' },
      { portal: '23-16', app: '23-05', focus: 'portal', title: 'Template builder drives the form', actor: 'Admin User',
        note: 'Seven field types in the palette, drag-ordered list, and per-field settings: required, share with volunteer, and conditional show/hide on another field’s answer. The live preview uses the app’s own components, and the phone beside it is the real result.',
        pins: [{ match: 'FIELD TYPES', text: 'All seven types' }, { match: 'Show only when', text: 'Conditional logic' }, { match: 'Share with volunteer', text: 'Controls what 23-13 shows' }, { match: 'LIVE PREVIEW', text: 'Reacts to the condition (rating = 2)' }],
        tryIt: 'Tap “Publish” to see the library.', ref: '§7.4 · S/N 23 · Portal 12' },
      { portal: '23-15', title: 'Template library', actor: 'Admin User',
        note: 'Templates are tagged to event types; the event card picks one. Archived versions stay linked to the feedback collected under them.',
        pins: [{ match: 'Used by', text: 'How many event cards use it' }, { match: 'Archived', text: 'Kept for past feedback' }],
        tryIt: 'Tap a template name to open the builder.', ref: '§7.4 · S/N 23 · Portal 11' },
      { app: '23-11', title: 'Volunteer: notifications', actor: 'Volunteer',
        note: 'The volunteer is told when feedback about their shift is submitted, and separately when a perfect rating earns points. Each type has its own icon and label.',
        pins: [{ match: 'Feedback submitted for your shift', text: 'New type' }, { match: 'You earned 50 CPFV points', text: 'Perfect-rating reward' }],
        tryIt: 'Tap the first notification.', ref: '§7.4 · S/N 23 · App 9' },
      { app: '23-12', title: 'Volunteer: Profile → My Feedback', actor: 'Volunteer',
        note: 'A “My Feedback” tab sits beside My Posts and My Comments on the existing Forum Profile. Perfect ratings show the points awarded.',
        pins: [{ match: 'My Feedback', text: 'New third tab' }, { match: '+50 points', text: 'Points for a 5 of 5' }],
        tryIt: 'Tap the Meals-on-Wheels entry.', ref: '§7.4 · S/N 23 · App 10' },
      { app: '23-13', title: 'Volunteer: feedback detail', actor: 'Volunteer',
        note: 'Only fields the template marks shareable appear: rating, the chips and the comment. Role, deploy-again and the attachment stay internal.',
        pins: [{ match: 'What the team noticed', text: 'Shareable chips only' }, { match: 'You only see the parts of the feedback', text: 'Rule stated to the volunteer' }],
        tryIt: 'Next: the Portal register.', ref: '§7.4 · S/N 23 · App 10' },
      { portal: '23-18', title: 'Feedback register', actor: 'Admin User',
        note: 'Filters for event, slot, author, subject, status and date. Export applies the current filters. The row drawer marks which fields were shared and shows the audit history.',
        pins: [{ match: 'Export CSV', text: 'CSV / XLSX with filters applied' }, { match: 'Overall rating · shared', text: 'Shared flag per field' }, { match: 'History:', text: 'Created / submitted timestamps' }],
        tryIt: 'Next: the roster at the largest text size.', ref: '§7.4 · S/N 23 · Portal 14' },
      { app: '23-14', title: 'Roster at largest text size', actor: 'Support-role user · 200% text',
        note: 'At 200% text the rows stack vertically, pills wrap to their own line and the action becomes a full-width button. Nothing is lost, nothing overlaps.',
        pins: [{ match: 'Give feedback', text: 'Full-width action at 200%' }],
        tryIt: 'Tap “Give feedback”.', ref: 'WCAG 2.1 AA · text scales to 200%' },
    ],
  },

  {
    id: '24', sn: 'S/N 24', title: 'Recognition feature', phase: 'Phase 2',
    intro: 'A Recognition feed of stories about volunteers, with in-app viewers for PDF, Office documents, audio and video, moderated comments and deep-link sharing. Published and moderated from the Portal.',
    rules: [
      'Recognition reuses the Forum post-card anatomy and lives under the What’s New tile; no new bottom tab.',
      'Every uploaded file is scanned: Scanning → Clean / Blocked. Blocked files cannot be published (24-12).',
      'Comments are reviewed before they appear (24-07, 24-13).',
      'Office documents are shown as converted PDF with the original available for download (24-04).',
    ],
    steps: [
      { app: '24-01', title: 'Recognition feed', actor: 'Volunteer',
        note: 'Opened from the What’s New tile, which gains two sub-tabs. Posts reuse the Forum card with cover media and a Latest | Trending control.',
        pins: [{ match: 'Recognition', text: 'New sub-tab beside What’s New' }, { match: 'Latest', text: 'Latest | Trending' }, { match: 'Video · 2:14', text: 'Media type and length on the card' }],
        tryIt: 'Tap the Volunteer of the Month card.', ref: '§7.4 · S/N 24 · App 1' },
      { app: '24-02', title: 'Post detail', actor: 'Volunteer',
        note: 'Media carousel, rich text, an embedded link preview and an attached document. Like, comment and share carry counters.',
        pins: [{ match: 'Citation letter.pdf', text: 'Opens the in-app PDF viewer' }, { match: 'example.org.sg', text: 'Embedded link preview' }, { match: '24 Comments', text: 'Moderated comments' }],
        tryIt: 'Tap “Citation letter.pdf”.', ref: '§7.4 · S/N 24 · App 2' },
      { app: '24-03', title: 'Viewer: PDF', actor: 'Volunteer',
        note: 'Page control, zoom and download, all inside the app.',
        pins: [{ match: 'Page 2 of 6', text: 'Page control' }],
        tryIt: 'Next: Office document.', ref: '§7.4 · S/N 24 · App 3' },
      { app: '24-04', title: 'Viewer: Office document', actor: 'Volunteer',
        note: 'Word, Excel and PowerPoint files are converted to PDF for reading. The original stays one tap away and a toast confirms the download.',
        pins: [{ match: 'Shown as a PDF for easy reading.', text: 'Converted copy' }, { match: 'Download original .docx', text: 'Original preserved' }],
        tryIt: 'Next: audio.', ref: '§7.4 · S/N 24 · App 3' },
      { app: '24-05', title: 'Viewer: audio (MP3)', actor: 'Volunteer',
        note: 'Player with scrub bar, 15-second skips and a transcript for accessibility.',
        pins: [{ match: 'Transcript', text: 'Text alternative' }],
        tryIt: 'Next: video.', ref: '§7.4 · S/N 24 · App 3' },
      { app: '24-06', title: 'Viewer: video (MP4)', actor: 'Volunteer',
        note: 'Full-screen player with a captions toggle and 10-second skips.',
        pins: [{ match: 'CC On', text: 'Captions toggle' }],
        tryIt: 'Tap ✕ to close.', ref: '§7.4 · S/N 24 · App 3' },
      { app: '24-07', title: 'Comment sheet', actor: 'Volunteer',
        note: 'The moderation notice is shown before anyone types. The volunteer’s own pending comment is visible to them only, labelled Pending review.',
        pins: [{ match: 'Comments are reviewed before they appear.', text: 'Moderation notice' }, { match: 'Pending review', text: 'Visible to author only' }],
        tryIt: 'Next: share sheet.', ref: '§7.4 · S/N 24 · App 4' },
      { app: '24-08', title: 'Share sheet', actor: 'Volunteer',
        note: 'Native share with a deep-link preview card. The link opens the post in the app, or the store page if the app is not installed.',
        pins: [{ match: 'Opens in the app', text: 'Deep link' }],
        tryIt: 'Next: how the post was published.', ref: '§7.4 · S/N 24 · App 4' },
      { portal: '24-12', app: '24-02', focus: 'portal', title: 'Portal post editor → app post', actor: 'Admin User',
        note: 'Title, rich text, media uploader with per-file scan status, embed URL, schedule and a preview-as-app pane. Scheduling stays disabled until every file is Clean. The phone shows the published result.',
        pins: [{ match: 'Scanning', text: 'Per-file scan status' }, { match: 'Blocked · macro found', text: 'Cannot publish' }, { match: 'Schedule is disabled until every file is scanned clean.', text: 'Rule enforced in the UI' }],
        tryIt: 'Tap “PREVIEW AS APP”.', ref: '§7.4 · S/N 24 · Portal 6' },
      { portal: '24-13', app: '24-07', focus: 'portal', title: 'Moderation queue and reach report', actor: 'Admin User',
        note: 'Approve or reject in bulk; flagged comments are highlighted. Reach is reported per post: views, likes, comments, shares and trending rank.',
        pins: [{ match: 'Flagged', text: 'Auto-flagged content' }, { match: 'Trending', text: 'Rank feeds the app’s Trending sort' }],
        tryIt: 'Next: processing state.', ref: '§7.4 · S/N 24 · Portal 7' },
      { app: '24-10', title: 'Upload processing state', actor: 'Volunteer',
        note: 'A video that is still being transcoded shows a clear placeholder; the rest of the post is readable.',
        pins: [{ match: 'Video is being prepared', text: 'Processing state' }],
        tryIt: 'Next: empty state.', ref: '§7.4 · S/N 24 · App 5' },
      { app: '24-09', title: 'Empty state', actor: 'Volunteer',
        note: 'Same composition as the Forum empty states: mascots, one line, lavender pill.',
        pins: [{ match: 'Stories of volunteers like you will appear here.', text: 'Existing empty-state pattern' }],
        tryIt: 'Next: 200% text.', ref: '§7.4 · S/N 24 · App 5' },
      { app: '24-11', title: 'Feed at largest text size', actor: 'Volunteer · 200% text',
        note: 'Counters stack and gain text labels so meaning is not carried by icons alone.',
        pins: [{ match: '312 likes', text: 'Icon gets a word' }],
        tryIt: 'Tap the post title.', ref: 'WCAG 2.1 AA' },
    ],
  },

  {
    id: '25', sn: 'S/N 25', title: 'Pre-requisites', phase: 'Phase 2',
    intro: 'Admins attach eligibility rules to a time slot. Ineligible volunteers see a named lock with what to do next; admins can override with a reason.',
    rules: [
      'Rules are predicate rows joined in AND / OR groups; a plain-language summary is generated (25-05).',
      'The app reuses the existing padlock overlay; the caption names the first unmet rule (25-01).',
      'Each unmet rule deep-links to the module or event that satisfies it (25-03).',
      'Overrides need a reason and are audited; the volunteer sees “Approved by CPFB” (25-06, 25-02).',
    ],
    steps: [
      { portal: '25-05', app: '25-01', focus: 'portal', title: 'Eligibility rules → named lock', actor: 'Admin User',
        note: 'Predicate types: profile attribute, Learn module completed, challenge completed, attended event, SHL step, user-group member. The generated summary is what the volunteer sees paraphrased on the lock.',
        pins: [{ match: 'GROUP A · ALL of', text: 'AND group' }, { match: 'OR', text: 'OR between groups' }, { match: 'Summary:', text: 'Generated plain language' }, { match: 'volunteers currently eligible', text: 'Live count' }],
        tryIt: 'Tap “Summary” to see the volunteer’s view.', ref: '§7.4 · S/N 25 · Portal 1' },
      { app: '25-01', title: 'Discover Events: named lock', actor: 'Volunteer',
        note: 'The existing dimmed card, padlock and mascot are reused exactly. Only the caption changes: it names the first unmet prerequisite instead of a task count.',
        pins: [{ match: 'Befriending Basics', text: 'Named prerequisite' }, { match: 'View Event', text: 'Existing yellow pill' }],
        tryIt: 'Tap “View Event”.', ref: '§7.4 · S/N 25 · App 3' },
      { app: '25-02', title: 'Time-slot card: three states', actor: 'Volunteer',
        note: 'Eligible with a Register button, locked with a one-line reason and a “What to do next” link, and admin-overridden with a small “Approved by CPFB” pill.',
        pins: [{ match: 'Locked: 2 steps to go', text: 'Locked state' }, { match: 'Approved by CPFB', text: 'Override pill' }, { match: 'What to do next', text: 'Opens the checklist' }],
        tryIt: 'Tap “What to do next”.', ref: '§7.4 · S/N 25 · App 3' },
      { app: '25-03', title: 'Locked detail sheet', actor: 'Volunteer',
        note: 'Each unmet rule deep-links to the module or event that satisfies it. Met rules are ticked and greyed. The OR alternative is spelled out.',
        pins: [{ match: '1 of 3 done', text: 'Progress' }, { match: 'Learn · 2 of 5 content viewed', text: 'Deep link into Learn' }, { match: 'Or be a member of', text: 'OR group from the Portal rule' }],
        tryIt: 'Next: the override.', ref: '§7.4 · S/N 25 · App 4' },
      { portal: '25-06', app: '25-02', focus: 'portal', title: 'Override → “Approved by CPFB”', actor: 'Admin User',
        note: 'The ineligible-attempts report shows who tried and which rule stopped them. Override needs a reason and an audit note; the volunteer’s slot card then shows the pill.',
        pins: [{ match: 'Unmet rule', text: 'Why registration failed' }, { match: 'Reason', text: 'Required' }, { match: 'Logged under your name', text: 'Audited' }],
        tryIt: 'Tap “Approve override”.', ref: '§7.4 · S/N 25 · Portal 2' },
      { app: '25-04', title: 'Lock sheet at largest text size', actor: 'Volunteer · 200% text',
        note: 'At 200% the sheet opens full-screen; status uses a text symbol and words, not colour.',
        pins: [{ match: 'In Learn', text: 'Location in words' }],
        tryIt: 'Next flow: Store mailing.', ref: 'WCAG 2.1 AA' },
    ],
  },

  {
    id: '26', sn: 'S/N 26', title: 'Store and mailing', phase: 'Phase 2',
    intro: 'Rewards can be mailed to a Singapore address. Volunteers choose self-collect or mail, enter an address with postal-code lookup, and track the parcel. Admins run a fulfilment queue with a mailing-house export.',
    rules: [
      'Mailable is a per-item setting; the mailing note on the item is shown to the volunteer (26-09, 26-02).',
      'Postal code lookup fills block and street; unit format is validated inline (26-03).',
      'Status timeline: Requested → Packed → Dispatched → Delivered → Acknowledged (26-06).',
      'A receipt reminder is sent N days after Dispatched; auto-acknowledge after M days (26-09, 26-07).',
      'Address edits by admins are audited (26-10).',
    ],
    steps: [
      { portal: '26-09', app: '26-01', focus: 'portal', title: 'Item settings → Mailable tag', actor: 'Admin User',
        note: 'Mailable toggle, stock, low-stock alert, the note volunteers see, and the reminder timings. The phone shows the tag and note on the reward.',
        pins: [{ match: 'Mailable', text: 'Per-item switch' }, { match: 'Mailing note shown to volunteer', text: 'Copied to 26-02' }, { match: 'Receipt reminder after', text: 'Drives 26-07' }],
        tryIt: 'Tap “Mailable”.', ref: '§7.4 · S/N 26 · Portal 4' },
      { app: '26-01', title: 'Reward detail', actor: 'Volunteer',
        note: 'Mailable tag, stock and points cost on the existing reward layout.',
        pins: [{ match: 'Mailable', text: 'New tag' }, { match: '300 points', text: 'Cost' }],
        tryIt: 'Tap “Redeem”.', ref: '§7.4 · S/N 26 · App 1' },
      { app: '26-02', title: 'Choose how to receive it', actor: 'Volunteer',
        note: 'Self-collect at CPFB or Mail to me. The mailing note comes from the Portal item settings. Points are deducted only on confirmation.',
        pins: [{ match: 'Mail to me', text: 'New option' }, { match: 'Free local mail', text: 'Note from 26-09' }],
        tryIt: 'Tap “Mail to me”.', ref: '§7.4 · S/N 26 · App 2' },
      { app: '26-03', title: 'Address form with postal lookup', actor: 'Volunteer',
        note: 'Postal code → block and street auto-fill. Unit, recipient and mobile are validated inline. “Save for next time” keeps the address for later redemptions.',
        pins: [{ match: 'Filled from postal code', text: 'Lookup' }, { match: 'Use the format #08-123', text: 'Inline validation' }, { match: 'Save for next time', text: 'Remembered address' }],
        tryIt: 'Tap “Review order”.', ref: '§7.4 · S/N 26 · App 2' },
      { app: '26-04', title: 'Confirmation', actor: 'Volunteer',
        note: 'Reference number, points used and the address, with a mascot. The reference matches the Portal queue.',
        pins: [{ match: 'RD-2026-10482', text: 'Same reference in the Portal' }],
        tryIt: 'Tap “View my redemptions”.', ref: '§7.4 · S/N 26 · App 3' },
      { portal: '26-10', app: '26-06', focus: 'portal', title: 'Fulfilment queue → status timeline', actor: 'Admin User',
        note: 'Bulk status update, CSV export for the mailing house, and a row drawer with an editable, audited address and the volunteer’s points history. Each status change moves the volunteer’s timeline.',
        pins: [{ match: 'Export CSV for mailing house', text: 'Mailing-house file' }, { match: 'Set status: Packed', text: 'Bulk update' }, { match: 'Audit trail', text: 'Address changes logged' }],
        tryIt: 'Next: the volunteer’s list.', ref: '§7.4 · S/N 26 · Portal 5' },
      { app: '26-05', title: 'My redemptions', actor: 'Volunteer',
        note: 'Under Store. Newest first; the pill shows the current step for mail orders and Collected for self-collect.',
        pins: [{ match: 'Dispatched', text: 'Current step' }],
        tryIt: 'Tap the tote bag.', ref: '§7.4 · S/N 26 · App 3' },
      { app: '26-06', title: 'Status timeline', actor: 'Volunteer',
        note: 'Five steps with dates, the tracking reference, and an “I have received it” button that closes the loop.',
        pins: [{ match: 'Tracking ref.', text: 'Copyable' }, { match: 'I have received it', text: 'Volunteer acknowledgement' }],
        tryIt: 'Next: the reminder.', ref: '§7.4 · S/N 26 · App 3' },
      { app: '26-07', title: 'Receipt reminder on Home', actor: 'Volunteer',
        note: 'Sent N days after Dispatched, as set in the Portal. “Not yet” alerts the fulfilment team.',
        pins: [{ match: 'Did your tote bag arrive?', text: 'Timed by 26-09' }, { match: 'Not yet', text: 'Flags the order' }],
        tryIt: 'Tap “Yes, received”.', ref: '§7.4 · S/N 26 · App 3' },
      { app: '26-08', title: 'Address form at largest text size', actor: 'Volunteer · 200% text',
        note: 'Labels stay above fields; the error keeps its symbol and words.',
        pins: [{ match: 'Use the format #08-123', text: 'Error at 200%' }],
        tryIt: 'Next flow: Profiles.', ref: 'WCAG 2.1 AA' },
    ],
  },

  {
    id: '27', sn: 'S/N 27', title: 'Profile discovery and engagement', phase: 'Phase 3',
    intro: 'Public profiles reachable from any name in Forum or the Leaderboard, search by Referrer name, follow / friends, a friends’ accomplishment feed with a Celebrate reaction, and profile sharing. Settings and moderation in the Portal.',
    rules: [
      '“Friends” means you follow each other (27-05).',
      'Only shareable feedback fields appear on a public profile (27-01).',
      'Private profiles show by name only, without Follow (27-03).',
      'The friends’ feed window and default visibility are Portal settings (27-10).',
    ],
    steps: [
      { app: '27-04', title: 'Entry points: Leaderboard and Forum post', actor: 'Volunteer',
        note: 'Names and avatars on the Leaderboard (“My Rank”) and on Forum posts become tappable. No new navigation is added.',
        pins: [{ match: 'Tap a name to open the profile', text: 'Existing lists, new tap target' }],
        tryIt: 'Tap “meilin.t”.', ref: '§7.4 · S/N 27 · App 3' },
      { app: '27-01', title: 'Public profile', actor: 'Volunteer',
        note: 'Cover, avatar with level, Referrer name, joined date, follower count, Follow button, stat tiles reused from Home, showcased badges and feedback highlights built only from shareable fields. ⋯ holds Block / Report.',
        pins: [{ match: '+ Follow', text: 'Follow / Following' }, { match: 'Feedback highlights', text: 'Shareable chips only, from S/N 23' }, { match: 'Showcased badges', text: 'Chosen by the owner' }],
        tryIt: 'Tap ↗ to share, or “128 followers”.', ref: '§7.4 · S/N 27 · App 1' },
      { app: '27-03', title: 'Search by Referrer name', actor: 'Volunteer',
        note: 'Forum search gains a People tab. Private profiles appear by name only, without Follow.',
        pins: [{ match: 'People', text: 'New search tab' }, { match: 'Private profile', text: 'No Follow, no details' }],
        tryIt: 'Tap a result.', ref: '§7.4 · S/N 27 · App 3' },
      { app: '27-02', title: 'Own profile: edit', actor: 'Volunteer',
        note: 'Cover picker, accent colour, choose up to three showcased achievements, and visibility: Everyone, Friends only, Private.',
        pins: [{ match: 'Showcase achievements', text: 'Pick 3' }, { match: 'Who can see my profile', text: 'Visibility' }],
        tryIt: 'Next: friends lists.', ref: '§7.4 · S/N 27 · App 2' },
      { app: '27-05', title: 'Friends: Following and Followers', actor: 'Volunteer',
        note: 'Opened from the Following count on Profile, where “Following: 0 Topics” sits today. Mutual follows are labelled Friends.',
        pins: [{ match: '"Friends" means you follow each other.', text: 'Definition on screen' }, { match: 'Highlights', text: 'Accomplishment feed' }],
        tryIt: 'Tap “Highlights”.', ref: '§7.4 · S/N 27 · App 4' },
      { app: '27-06', title: 'Friends’ accomplishment feed', actor: 'Volunteer',
        note: 'Badges earned, event milestones and level-ups from friends, within a rolling window set in the Portal. Celebrate is a single reaction; no comments.',
        pins: [{ match: 'Celebrate', text: 'One reaction only' }, { match: 'Showing the last 14 days', text: 'Window from 27-10' }],
        tryIt: 'Next: Home toasts.', ref: '§7.4 · S/N 27 · App 4' },
      { app: '27-07', title: 'Home toasts: friend vs non-friend', actor: 'Volunteer',
        note: 'Friend variant has the avatar, a “Your friend” label and Celebrate. Non-friend variant uses a generic icon and names the person only if their profile is public.',
        pins: [{ match: 'Your friend', text: 'Friend variant' }, { match: 'A volunteer in Toa Payoh', text: 'Non-friend, anonymised' }],
        tryIt: 'Tap “View profile”.', ref: '§7.4 · S/N 27 · App 5' },
      { app: '27-08', title: 'Shared profile link preview', actor: 'Recipient in a messaging app',
        note: 'The Open Graph card as it appears in WhatsApp or Telegram: avatar, level, headline stats and a deep link into the app.',
        pins: [{ match: 'meilin.t on CPF Volunteer', text: 'OG title' }],
        tryIt: 'Tap the link card.', ref: '§7.4 · S/N 27 · App 6' },
      { portal: '27-10', app: '27-06', focus: 'portal', title: 'Portal settings, reports, engagement', actor: 'Admin User',
        note: 'Feed window in days, default visibility for new users, the non-friend toast switch, an engagement report and the reported-profile moderation list.',
        pins: [{ match: "Friends' feed window", text: 'Drives “last 14 days”' }, { match: 'Reported profiles', text: 'Moderation' }, { match: 'Engagement · last 30 days', text: 'Report' }],
        tryIt: 'Tap “Friends’ feed window”.', ref: '§7.4 · S/N 27 · Portal 7' },
      { app: '27-09', title: 'Public profile at largest text size', actor: 'Volunteer · 200% text',
        note: 'Stat tiles become a labelled list at 200%.',
        pins: [{ match: '64 events attended', text: 'Tile → list row' }],
        tryIt: 'Next flow: Calendar.', ref: 'WCAG 2.1 AA' },
    ],
  },

  {
    id: '28', sn: 'S/N 28', title: 'Calendar', phase: 'Phase 3',
    intro: 'My Activities gains a calendar / list toggle. Dots encode status by shape and colour, categories take their colour from a Portal legend, and SHL deployments render in a distinct style.',
    rules: [
      'The toggle reuses the Missions | VFTP segmented control (28-01).',
      'Status is never shown by colour alone: ring, filled, square (28-01, 28-09).',
      'Events appear only if “Show in volunteer calendar” is on for the event (28-08).',
    ],
    steps: [
      { app: '28-01', title: 'Month view', actor: 'Volunteer',
        note: 'Dots differ by shape as well as colour. Tapping a day shows its events below the grid.',
        pins: [{ match: 'Calendar', text: 'List | Calendar toggle' }, { match: 'Registered', text: 'Legend: ring, filled, squares' }, { match: 'SAT 18 OCT · 2:00 PM', text: 'Selected day' }],
        tryIt: 'Tap “List”, Filter, or the 24th.', ref: '§7.4 · S/N 28 · App 1' },
      { app: '28-02', title: 'Agenda list view', actor: 'Volunteer',
        note: 'Upcoming then past. The left bar is the category colour from the Portal legend; the status pill sits on the right.',
        pins: [{ match: 'SHL deployment · Bishan CC', text: 'Distinct SHL style' }, { match: 'No-show', text: 'Links to S/N 29' }],
        tryIt: 'Tap “SHL deployment · Bishan CC”.', ref: '§7.4 · S/N 28 · App 1' },
      { app: '28-03', title: 'Filter sheet', actor: 'Volunteer',
        note: 'Category and status filters with a live count on the button.',
        pins: [{ match: 'Show 6 events', text: 'Live count' }],
        tryIt: 'Tap “Show 6 events”.', ref: '§7.4 · S/N 28 · App 2' },
      { app: '28-04', title: 'Event detail and “Add to my calendar”', actor: 'Volunteer',
        note: 'Tap-through to the existing event detail. “Add to my calendar” writes to the device calendar and confirms with a reminder note.',
        pins: [{ match: 'Added to your calendar', text: 'Confirmation' }],
        tryIt: 'Next: the Portal side.', ref: '§7.4 · S/N 28 · App 2' },
      { portal: '28-08', app: '28-05', focus: 'portal', title: 'Event calendar settings → SHL day view', actor: 'Admin User',
        note: 'The event card’s Calendar tab: “Show in volunteer calendar” and the calendar type. The app preview and the phone show the distinct SHL rendering.',
        pins: [{ match: 'Show in volunteer calendar', text: 'Per-event switch' }, { match: 'SHL deployment · distinct style', text: 'Type from the legend' }],
        tryIt: 'Tap “SHL deployment · distinct style”.', ref: '§7.4 · S/N 28 · Portal 4' },
      { app: '28-05', title: 'Differentiated SHL day view', actor: 'Volunteer',
        note: 'SHL deployments carry reporting details: station, who to report to, what to bring. Other events on the day are listed below.',
        pins: [{ match: 'Report to:', text: 'SHL-specific fields' }],
        tryIt: 'Next: the legend editor.', ref: '§7.4 · S/N 28 · App 3' },
      { portal: '28-09', title: 'Calendar legend editor', actor: 'Admin User',
        note: 'Types, colours and card styles in one place. The palette is limited so colours stay distinct and AA-contrast on white.',
        pins: [{ match: 'Hatched + dashed', text: 'SHL card style' }, { match: 'Colour choices', text: 'Constrained palette' }],
        tryIt: 'Next: empty month.', ref: '§7.4 · S/N 28 · Portal 4' },
      { app: '28-06', title: 'Empty month', actor: 'Volunteer',
        note: 'Mascot empty state with a direct route to Discover Events.',
        pins: [{ match: 'Nothing planned for November yet', text: 'Empty state' }],
        tryIt: 'Tap “Browse Upcoming Events”.', ref: '§7.4 · S/N 28 · App 3' },
      { app: '28-07', title: 'Agenda at largest text size', actor: 'Volunteer · 200% text',
        note: 'At 200% the month grid is replaced by the agenda and dates are written out in full. The SHL marker keeps its shape and label.',
        pins: [{ match: 'Saturday 18 October', text: 'Date written in full' }, { match: 'SHL deployment', text: 'Shape + words' }],
        tryIt: 'Next flow: No-show penalty.', ref: 'WCAG 2.1 AA' },
    ],
  },

  {
    id: '29', sn: 'S/N 29', title: 'No-show penalty', phase: 'Phase 4',
    intro: 'A per-event-type policy marks no-shows, warns volunteers, and pauses registration after a threshold. Admins can correct attendance, lift blocks early, and export the full history.',
    rules: [
      'Policy per event type: days before auto no-show, threshold within a window, block duration (29-07).',
      'Warnings use the yellow of the tab bar; the blocked state reuses the dimmed-card pattern (29-01, 29-03).',
      'Editing attendance recomputes counters and needs a reason (29-08).',
      'History keeps six data points: no-show dates, block dates, lift dates, running block count, counter, reset marker (29-09).',
    ],
    steps: [
      { portal: '29-07', app: '29-01', focus: 'portal', title: 'Penalty policy → warning banner', actor: 'Admin User',
        note: 'Per event type: when to auto-mark a no-show, the threshold and window, the block duration and which event cards it applies to. The preview sentence is what the volunteer reads.',
        pins: [{ match: 'Threshold', text: '3 in 90 days' }, { match: 'Block duration', text: '30 days' }, { match: 'Preview:', text: 'Same words as the app' }],
        tryIt: 'Tap “Preview”.', ref: '§7.4 · S/N 29 · Portal 4' },
      { app: '29-01', title: 'Warning banner on Home', actor: 'Volunteer',
        note: 'After the first no-show, a yellow banner states the count and the consequence in one sentence.',
        pins: [{ match: '1 of 3 no-shows', text: 'Running count' }, { match: 'See details', text: 'Attendance record' }],
        tryIt: 'Tap “See details”.', ref: '§7.4 · S/N 29 · App 1' },
      { app: '29-02', title: 'Event marked No-show', actor: 'Volunteer',
        note: 'The event in history shows the no-show, the window it counts in, how to avoid it next time, and a route to dispute it.',
        pins: [{ match: "You registered but didn't check in.", text: 'Plain explanation' }, { match: 'I was there. Contact CPFB', text: 'Dispute route' }],
        tryIt: 'Next: blocked state.', ref: '§7.4 · S/N 29 · App 1' },
      { app: '29-03', title: 'Blocked: Discover Events', actor: 'Volunteer',
        note: 'After the third no-show, a banner gives the lift date and each card shows when registration reopens, using the dimmed-card pattern with a red-orange padlock variant.',
        pins: [{ match: 'Registration paused until', text: 'Lift date up front' }, { match: 'Why is this?', text: 'Explains the rule' }],
        tryIt: 'Tap “Why is this?”.', ref: '§7.4 · S/N 29 · App 2' },
      { app: '29-04', title: 'Notifications: warning, block, lift', actor: 'Volunteer',
        note: 'Three notification types across the penalty lifecycle, newest first.',
        pins: [{ match: 'You can register again', text: 'Lift' }, { match: 'Registration paused for 30 days', text: 'Block' }, { match: 'No-show recorded', text: 'Warning' }],
        tryIt: 'Tap “No-show recorded”.', ref: '§7.4 · S/N 29 · App 2' },
      { app: '29-05', title: 'Attendance record', actor: 'Volunteer',
        note: 'The volunteer’s own no-show and block history under Profile.',
        pins: [{ match: 'No-shows in the last 90 days', text: 'Rolling window' }, { match: 'Block 1 · 30 days', text: 'Block entry' }],
        tryIt: 'Next: admin correction.', ref: '§7.4 · S/N 29 · App 3' },
      { portal: '29-08', app: '29-05', focus: 'portal', title: 'Attendance edit recomputes counters', actor: 'Admin User',
        note: 'The event card’s “Apply no-show penalty” toggle, and an attendance page where changing a status recalculates the volunteer’s counter immediately. A reason is required on save.',
        pins: [{ match: 'Apply no-show penalty', text: 'Per-event switch' }, { match: 'recalculated her counter', text: 'Live recompute' }],
        tryIt: 'Tap “Until 14 Nov”.', ref: '§7.4 · S/N 29 · Portal 5' },
      { portal: '29-09', app: '29-04', focus: 'portal', title: 'History report and manual lift', actor: 'Admin User',
        note: 'Six data points per volunteer with export, and a lift dialog that needs a reason and can reset the counter. The volunteer receives the lift notification.',
        pins: [{ match: 'Reset', text: 'Reset marker' }, { match: 'Lift block early', text: 'Manual lift with reason' }],
        tryIt: 'Tap “Lift block”.', ref: '§7.4 · S/N 29 · Portal 6' },
      { app: '29-06', title: 'Blocked at largest text size', actor: 'Volunteer · 200% text',
        note: 'The disabled Register button keeps a text reason and the lift date at 200%.',
        pins: [{ match: 'Register (paused)', text: 'Disabled, with the reason in words' }],
        tryIt: 'Next flow: User groups.', ref: 'WCAG 2.1 AA' },
    ],
  },

  {
    id: '30', sn: 'S/N 30', title: 'User groups', phase: 'Phase 4',
    intro: 'Static or dynamic groups of volunteers, built by search, CSV or rule. Events can be restricted to groups; non-members either see a “By invitation” card or do not see the event at all. The Authority chooses which.',
    rules: [
      'Dynamic groups reuse the S/N 25 predicate builder (30-01).',
      'CSV upload validates every row and reports errors before adding anyone (30-02).',
      'Restriction is set per event with an audit trail (30-03).',
      'Both non-member behaviours are designed (30-05, 30-06); one will be chosen.',
    ],
    steps: [
      { portal: '30-01', title: 'Groups list and create', actor: 'Admin User',
        note: 'Static groups are filled by search or CSV; dynamic groups update by rule. The rule builder is the one from S/N 25, so admins learn it once.',
        pins: [{ match: 'Dynamic', text: 'Rule-based membership' }, { match: 'Same predicate builder as S/N 25 eligibility rules.', text: 'Shared component' }],
        tryIt: 'Tap “SHL Guides”.', ref: '§7.4 · S/N 30 · Portal 1' },
      { portal: '30-02', title: 'Add members by CSV', actor: 'Admin User',
        note: 'Every row is checked. Ready, already-member and error counts are shown before anything is added; error rows can be downloaded and fixed.',
        pins: [{ match: 'Ready to add', text: 'Validated rows' }, { match: 'Download error rows', text: 'Fix and re-upload' }],
        tryIt: 'Tap “Add 48 members”.', ref: '§7.4 · S/N 30 · Portal 1' },
      { portal: '30-03', app: '30-06', focus: 'portal', title: 'Restrict an event → non-member view', actor: 'Admin User',
        note: 'The event card’s Access tab: who can register, which groups, and how non-members see it. Changes are audited and usage is reported. The phone shows the non-member card.',
        pins: [{ match: 'Only these groups', text: 'Restriction to SHL Guides' }, { match: 'Non-members', text: 'Authority’s choice: label or hide' }, { match: 'Audit trail', text: 'Who restricted it, when' }, { match: 'Usage', text: 'Membership and usage report' }],
        tryIt: 'Tap “Hide from the event list” or “Only these groups” to see each app result.', ref: '§7.4 · S/N 30 · Portal 2' },
      { app: '30-04', title: 'Member sees a normal event', actor: 'Volunteer · group member',
        note: 'Members see the event as any other, with a small group chip.',
        pins: [{ match: 'SHL Guides', text: 'Group chip' }],
        tryIt: 'Next: non-member, option B.', ref: '§7.4 · S/N 30 · App 3' },
      { app: '30-06', title: 'Non-member: “By invitation” card', actor: 'Volunteer · not a member',
        note: 'Option B. The card stays listed with a “By invitation” chip and no Register button.',
        pins: [{ match: 'By invitation', text: 'Label replaces slots' }, { match: 'For SHL Guides', text: 'Names the group' }],
        tryIt: 'Tap “View details”.', ref: '§7.4 · S/N 30 · App 3' },
      { app: '30-07', title: 'Non-member: invitation message', actor: 'Volunteer · not a member',
        note: 'Opening the event gives a clear message and a route to join the programme.',
        pins: [{ match: 'This event is by invitation', text: 'Clear message' }, { match: 'About SHL Guides', text: 'Route to join' }],
        tryIt: 'Next: option A.', ref: '§7.4 · S/N 30 · App 3' },
      { app: '30-05', title: 'Non-member: hidden from the list', actor: 'Volunteer · not a member',
        note: 'Option A. The restricted event simply does not appear; a deep link still opens the message in 30-07. Both options are built; the Authority will choose.',
        pins: [{ match: 'SHL deployment not listed for non-members', text: 'Annotation, not UI' }],
        tryIt: 'Next: 200% text.', ref: '§7.4 · S/N 30 · App 3' },
      { app: '30-08', title: 'Invitation message at largest text size', actor: 'Volunteer · 200% text',
        note: 'Message and action stay readable with no truncation.',
        pins: [{ match: 'About SHL Guides', text: 'Full-width action' }],
        tryIt: 'Next: cross-cutting screens.', ref: 'WCAG 2.1 AA' },
    ],
  },

  {
    id: 'X', sn: 'Cross-cutting', title: 'Shared screens', phase: 'All phases',
    intro: 'Screens that several enhancements share: the notification centre with the new types, privacy and language settings, and the shared error and offline patterns.',
    rules: [
      'Every new notification type has its own icon and a text label.',
      'Layouts tolerate strings about 30% longer than English for the languages to come.',
    ],
    steps: [
      { app: 'X-01', title: 'Notification centre', actor: 'Volunteer',
        note: 'The new types from S/N 23, 24, 26, 27 and 29 with consistent iconography and filters. Each row deep-links into its flow.',
        pins: [{ match: 'S/N 23 · Feedback', text: 'Deep-links to 23-02' }, { match: 'S/N 29 · Attendance', text: 'Deep-links to 29-02' }],
        tryIt: 'Tap any row.', ref: '§7.4 · cross-cutting' },
      { app: 'X-02', title: 'Settings → Privacy', actor: 'Volunteer',
        note: 'Profile visibility, feed participation, feedback-highlight sharing and blocked users in one place.',
        pins: [{ match: 'Share my feedback highlights', text: 'Links S/N 23 and S/N 27' }, { match: 'BLOCKED USERS', text: 'From S/N 27 Block' }],
        tryIt: 'Tap “Everyone ›”.', ref: '§7.4 · cross-cutting' },
      { app: 'X-03', title: 'Settings → Language placeholder', actor: 'Volunteer',
        note: 'Four languages listed; three marked Coming soon. Layouts are already built for the longer strings.',
        pins: [{ match: 'Layouts are built to take strings about 30% longer than English.', text: 'i18n note' }],
        tryIt: 'Next: error state.', ref: 'Brief §1 · languages' },
      { app: 'X-04', title: 'Error state', actor: 'Volunteer',
        note: 'Shared pattern: mascot, one line, retry, and a reference code for support.',
        pins: [{ match: 'Ref. ERR-5021', text: 'Support reference' }],
        tryIt: 'Tap “Try again”.', ref: '§7.4 · cross-cutting' },
      { app: 'X-05', title: 'Offline state', actor: 'Volunteer',
        note: 'Saved content stays readable with a clear offline banner.',
        pins: [{ match: "You're offline. Showing saved posts.", text: 'Offline banner' }],
        tryIt: 'That is the end of the walkthrough. Press M for the flow map.', ref: '§7.4 · cross-cutting' },
    ],
  },
];
